name: Backend CI/CD âš™ï¸

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build & Push Node Backend Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: "aniuser"
          password: "dckr_pat_-ktgFv9zbZemgourVtBJzSlPtoI"

      - name: Get latest version tag
        id: get_tag
        run: |
          latest_tag=$(curl -s https://hub.docker.com/v2/repositories/aniuser/node-backend/tags/?page_size=1 | jq -r '.results[0].name')
          if [[ "$latest_tag" =~ ^v[0-9]+$ ]]; then
            version=${latest_tag#v}
            new_tag="v$((version + 1))"
          else
            new_tag="v1"
          fi
          echo "TAG=$new_tag" >> $GITHUB_ENV
          echo "ğŸ”¥ New Docker Tag: $new_tag"

      - name: Build and Push Docker Images
        run: |
          cd docker-nodejs-sample
          docker build -t aniuser/node-backend:${{ env.TAG }} .
          docker tag aniuser/node-backend:${{ env.TAG }} aniuser/node-backend:latest
          
          docker push aniuser/node-backend:${{ env.TAG }}
          docker push aniuser/node-backend:latest
          
          echo "âœ… Successfully pushed:"
          echo "â¡ï¸ aniuser/node-backend:${{ env.TAG }}"
          echo "â¡ï¸ aniuser/node-backend:latest"
