name: Backend CI/CD âš™ï¸

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build & Push Node Backend Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: "aniuser"
          password: "dckr_pat_-ktgFv9zbZemgourVtBJzSlPtoI"

      - name: Set version tag
        id: vars
        run: |
          TAG=v$(date +'%Y%m%d%H%M')
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "ğŸ”¥ Using Docker tag: $TAG"

      - name: Build and Push Docker Images
        run: |
          cd docker-nodejs-sample
          docker build -t aniuser/node-backend:${{ env.TAG }} .
          docker tag aniuser/node-backend:${{ env.TAG }} aniuser/node-backend:latest
          
          docker push aniuser/node-backend:${{ env.TAG }}
          docker push aniuser/node-backend:latest
          
          echo "âœ… Successfully pushed:"
          echo "â¡ï¸ aniuser/node-backend:${{ env.TAG }}"
          echo "â¡ï¸ aniuser/node-backend:latest"

      - name: Verify Images on Local Docker
        run: |
          echo "ğŸ§¾ Listing local images..."
          docker images aniuser/node-backend
